/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ScrollToTopBtn {
    'direction': string;
    'mode': string;
  }
  interface ScrollToTopBtnAttributes extends StencilHTMLAttributes {
    'direction'?: string;
    'mode'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ScrollToTopBtn': Components.ScrollToTopBtn;
  }

  interface StencilIntrinsicElements {
    'scroll-to-top-btn': Components.ScrollToTopBtnAttributes;
  }


  interface HTMLScrollToTopBtnElement extends Components.ScrollToTopBtn, HTMLStencilElement {}
  var HTMLScrollToTopBtnElement: {
    prototype: HTMLScrollToTopBtnElement;
    new (): HTMLScrollToTopBtnElement;
  };

  interface HTMLElementTagNameMap {
    'scroll-to-top-btn': HTMLScrollToTopBtnElement
  }

  interface ElementTagNameMap {
    'scroll-to-top-btn': HTMLScrollToTopBtnElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
