/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ScrollToTopBtn {
    /**
    * Property that defines the bottom position of the button (in px)
    */
    'bottom': number;
    /**
    * Property that defines the direction of the scroll (for now only the "top" direction is available)
    */
    'direction': string;
    /**
    * Property that defines mode of the button (can be "light" or "dark")
    */
    'mode': string;
    /**
    * Property that defines the right position of the button (in px)
    */
    'right': number;
  }
  interface ScrollToTopBtnAttributes extends StencilHTMLAttributes {
    /**
    * Property that defines the bottom position of the button (in px)
    */
    'bottom'?: number;
    /**
    * Property that defines the direction of the scroll (for now only the "top" direction is available)
    */
    'direction'?: string;
    /**
    * Property that defines mode of the button (can be "light" or "dark")
    */
    'mode'?: string;
    /**
    * Property that defines the right position of the button (in px)
    */
    'right'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ScrollToTopBtn': Components.ScrollToTopBtn;
  }

  interface StencilIntrinsicElements {
    'scroll-to-top-btn': Components.ScrollToTopBtnAttributes;
  }


  interface HTMLScrollToTopBtnElement extends Components.ScrollToTopBtn, HTMLStencilElement {}
  var HTMLScrollToTopBtnElement: {
    prototype: HTMLScrollToTopBtnElement;
    new (): HTMLScrollToTopBtnElement;
  };

  interface HTMLElementTagNameMap {
    'scroll-to-top-btn': HTMLScrollToTopBtnElement
  }

  interface ElementTagNameMap {
    'scroll-to-top-btn': HTMLScrollToTopBtnElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
